//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// PresetTool.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_PRESETTOOL_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PANO                 130
#define IDD_PANO_DIALOG                 130
#define IDD_CEPH_DIALOG                 131
#define IDD_CT_DIALOG                   132
#define IDC_MAIN_TAB                    1000
#define IDC_CEPH_EXIST_STATIC           1001
#define IDC_CEPH_ALPHA_STATIC           1001
#define IDC_CEPH_APPLY_STATIC           1002
#define IDC_CEPH_BETA_STATIC            1002
#define IDC_CT_EXIST_STATIC             1003
#define IDC_CT_ALPHA_STATIC             1003
#define IDC_CT_APPLY_STATIC             1004
#define IDC_CT_BETA_STATIC              1004
#define IDC_PANO_EXIST_STATIC           1005
#define IDC_PANO_ALPHA_STATIC           1005
#define IDC_PANO_APPLY_STATIC           1006
#define IDC_PANO_BETA_STATIC            1006
#define IDC_EQUIPMENT_STATIC            1007
#define IDC_EQUIPMENT_NAME_STATIC       1008
#define IDC_PANO_STATIC                 1009
#define IDC_PANO_VERSION_STATIC         1010
#define IDC_CT_STATIC                   1011
#define IDC_CEPH_STATIC                 1012
#define IDC_CEPH_VERSION_STATIC         1013
#define IDC_CT_VERSION_STATIC           1014
#define IDC_PANO_RECENT_LOAD_BUTTON     1015
#define IDC_CT_COPYRIGHT_STATIC         1015
#define IDC_CEPH_RECENT_LOAD_BUTTON     1016
#define IDC_CT_SW_VERSION_STATIC        1016
#define IDC_PANO_COPYRIGHT_STATIC       1016
#define IDC_CEPH_PAST_LOAD_BUTTON       1017
#define IDC_SW_VERSION_STATIC2          1017
#define IDC_PANO_SW_VERSION_STATIC      1017
#define IDC_PANO_PAST_LOAD_BUTTON       1018
#define IDC_CEPH_SAMPLE_LOAD_BUTTON     1018
#define IDC_PANO_SAMPLE_LOAD_BUTTON     1019
#define IDC_CEPH_SW_VERSION_STATIC      1019
#define IDC_CT_RECENT_LOAD_BUTTON       1020
#define IDC_CEPH_APPLY_BUTTON           1020
#define IDC_CT_PAST_LOAD_BUTTON         1021
#define IDC_CEPH_SAVE_BUTTON            1021
#define IDC_CT_SAMPLE_LOAD_BUTTON       1022
#define IDC_CEPH_EXIT_BUTTON            1022
#define IDC_PANO_PROGRESS               1023
#define IDC_CT_APPLY_BUTTON             1023
#define IDC_CEPH_PROGRESS               1024
#define IDC_CT_SAVE_BUTTON              1024
#define IDC_CT_PROGRESS                 1025
#define IDC_CEPH_PRESET1_BUTTON         1026
#define IDC_CT_EXIT_BUTTON              1026
#define IDC_CEPH_PRESET_GROUPBOX        1027
#define IDC_CT_PRESET_GROUPBOX          1028
#define IDC_CEPH_PRESET2_BUTTON         1028
#define IDC_PANO_PRESET_GROUPBOX        1029
#define IDC_CEPH_PRESET3_BUTTON         1029
#define IDC_CT_PRESET2_BUTTON           1029
#define IDC_CEPH_PRESET4_BUTTON         1030
#define IDC_PANO_PRESET3_BUTTON         1030
#define IDC_CEPH_PRESET5_BUTTON         1031
#define IDC_PANO_PRESET4_BUTTON         1031
#define IDC_CEPH_PRESET6_BUTTON         1032
#define IDC_PANO_PRESET5_BUTTON         1032
#define IDC_CEPH_PRESET7_BUTTON         1033
#define IDC_PANO_PRESET6_BUTTON         1033
#define IDC_CEPH_PRESET8_BUTTON         1034
#define IDC_PANO_PRESET7_BUTTON         1034
#define IDC_CEPH_PRESET9_BUTTON         1035
#define IDC_PANO_PRESET8_BUTTON         1035
#define IDC_CEPH_PRESET10_BUTTON        1036
#define IDC_PANO_PRESET9_BUTTON         1036
#define IDC_CEPH_PRESET11_BUTTON        1037
#define IDC_PANO_PRESET10_BUTTON        1037
#define IDC_CEPH_PRESET12_BUTTON        1038
#define IDC_PANO_PRESET11_BUTTON        1038
#define IDC_PANO_PRESET12_BUTTON        1039
#define IDC_CT_PRESET1_BUTTON           1040
#define IDC_CT_PRESET3_BUTTON           1041
#define IDC_CT_PRESET4_BUTTON           1042
#define IDC_CT_PRESET5_BUTTON           1043
#define IDC_CT_PRESET6_BUTTON           1044
#define IDC_CT_PRESET7_BUTTON           1045
#define IDC_CT_PRESET8_BUTTON           1046
#define IDC_CT_PRESET9_BUTTON           1047
#define IDC_CT_PRESET10_BUTTON          1048
#define IDC_CT_PRESET11_BUTTON          1049
#define IDC_CT_PRESET12_BUTTON          1050
#define IDC_PANO_PRESET1_BUTTON         1051
#define IDC_PANO_PRESET2_BUTTON         1052
#define IDC_CEPH_COPYRIGHT_STATIC       1053
#define IDC_CEPH_CLAHE_SLIDER           1055
#define IDC_CEPH_UNSHARP_SLIDER         1056
#define IDC_CEPH_MEDIAN_SLIDER          1057
#define IDC_CEPH_CLAHE_EDIT             1058
#define IDC_CEPH_UNSHARP_EDIT           1059
#define IDC_CEPH_MEDIAN_EDIT            1060
#define IDC_CEPH_CLAHE_STATIC           1061
#define IDC_CEPH_UNSHARP_STATIC         1062
#define IDC_CEPH_MEDIAN_STATIC          1063
#define IDC_CEPH_CLAHE_SPIN             1064
#define IDC_CEPH_UNSHARP_SPIN           1065
#define IDC_CEPH_MEDIAN_SPIN            1066
#define IDC_CEPH_EFFECT_STATIC          1068
#define IDC_CEPH_CONTROLLER_STATIC      1069
#define IDC_CT_EFFECT_STATIC            1071
#define IDC_CT_CLAHE_STATIC             1072
#define IDC_CT_UNSHARP_STATIC           1073
#define IDC_CT_MEDIAN_STATIC            1074
#define IDC_CT_CLAHE_SLIDER             1075
#define IDC_CT_CLAHE_EDIT               1076
#define IDC_CT_CLAHE_SPIN               1077
#define IDC_CT_UNSHARP_SLIDER           1078
#define IDC_CT_UNSHARP_EDIT             1079
#define IDC_CT_UNSHARP_SPIN             1080
#define IDC_CT_MEDIAN_SLIDER            1081
#define IDC_CT_MEDIAN_EDIT              1082
#define IDC_CT_MEDIAN_SPIN              1083
#define IDC_CT_CONTROLLER_STATIC        1084
#define IDC_PANO_CLAHE_STATIC           1085
#define IDC_PANO_CLAHE_SLIDER           1086
#define IDC_PANO_CLAHE_EDIT             1087
#define IDC_PANO_CLAHE_SPIN             1088
#define IDC_PANO_EFFECT_STATIC          1089
#define IDC_PANO_UNSHARP_STATIC         1090
#define IDC_PANO_UNSHARP_SLIDER         1091
#define IDC_PANO_UNSHARP_EDIT           1092
#define IDC_PANO_UNSHARP_SPIN           1093
#define IDC_PANO_MEDIAN_STATIC          1094
#define IDC_PANO_MEDIAN_SLIDER          1095
#define IDC_PANO_MEDIAN_EDIT            1096
#define IDC_PANO_MEDIAN_SPIN            1097
#define IDC_PANO_CONTROLLER_STATIC      1098
#define IDC_PANO_APPLY_BUTTON           1099
#define IDC_PANO_SAVE_BUTTON            1100
#define IDC_PANO_EXIT_BUTTON            1101
#define IDC_PANO_CLAHE_EDIT2            1102
#define IDC_PANO_ALPHA_BUTTON           1102
#define IDC_PANO_BETA_BUTTON            1103
#define IDC_CEPH_ALPHA_BUTTON           1104
#define IDC_CEPH_BETA_BUTTON            1105
#define IDC_CT_ALPHA_BUTTON             1106
#define IDC_CT_BETA_BUTTON              1107
#define IDC_PANO_REMOVEA_BUTTON         1108
#define IDC_PANO_REMOVEB_BUTTON         1109
#define IDC_CT_REMOVEB_BUTTON           1110
#define IDC_CT_REMOVEA_BUTTON           1111
#define IDC_CEPH_REMOVEA_BUTTON         1112
#define IDC_CEPH_REMOVEB_BUTTON         1113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
